name: Metrics
on:
  # Roda todo dia à meia-noite
  schedule: [{cron: "0 0 * * *"}]
  # Roda se você der push na master/main
  push: {branches: ["master", "main"]}
  # Permite rodar manualmente na aba Actions
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu token pessoal (precisa criar um PAT se não tiver)
          token: ${{ secrets.METRICS_TOKEN }}

          # Configurações visuais
          user: gabrielrdc1
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          
          # Plugin de Linguagens (substitui o que você está usando)
          plugin_languages: yes
          plugin_languages_ignored: "html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot"
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_details: percentage
          
          # Ignorar repositórios específicos
          repositories_skipped: |
            Exercise-Recommendation-App-Using-Expert-Systems
